language: generic
dist: trusty
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
        - COMPILER_NAME=gcc
        - CC=gcc-4.9
        - CXX=g++-4.9
	- BUILD_TYPE=Debug
        - TEST_TARGET=test

    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
      env:
        - COMPILER_NAME=clang
        - CC=clang-4.0
        - CXX=clang++-4.0
	- BUILD_TYPE=Debug
        - TEST_TARGET=test

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
        - COMPILER_NAME=gcc
        - CC=gcc-4.9
        - CXX=g++-4.9
        - COVERAGE_CMAKE=-DCOVERALLS=ON
	- BUILD_TYPE=Debug
        - TEST_TARGET=coveralls

    - os: linux
      env:
        - BUILD_TYPE=Debug
        - TEST_TARGET=test

    - os: osx
      compiler: clang
# we may need to install libcurl, valgrind, and the custom version of libcurl
# that is built against gnutls.
script:
  - printenv
  - cmake --version
  - mkdir build
  - cd build
  - cmake -C ${BUILD_TYPE} ${COVERAGE_CMAKE} ..
  - make
  - make ${TEST_TARGET}
